[package]
name = "shell-main"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rscript = { path = "../../../" }
shell-api = { path = "../shell-api/" }
